### ISSUE TITLE
Add dynamic export capacity for Composite

### ISSUE THREAD

**Issue by snybril** [AdeleResearchGroup/ApAM#123]
Hint from German : Could use substitution on the state property (maybe the state property should be defined as a property of the composite)

**Comment by gevegab** [comment]
It is possible to use substitution in import/export match expressions. 

The substitution variable $this refers in this case to the source composite for imports, and to the target composite for exports. So, it is possible to refer to properties of the source/target composite for imports/exports respectively.

see test CompositeTest.CompositeContentMngtExportGlobalDynamicInstance for an example.

The state of the composite is currently a concept only used in the conflict manager to handle grant of owned instances. It has nothing to do with visibility, so no changes were made
