### ISSUE TITLE
Should remove optional manager names hardcoded in CST.java

### ISSUE THREAD

**Issue by snybril** [AdeleResearchGroup/ApAM#128]
At least DISTRIMAN, OBRMAN, HISTMAN should not be there.
	// Managers
	// TODO : Some of these are optional manager that should not be there (distriman, obrman for instance)
	public static final String APAMMAN   = "APAMMAN";
	public static final String CONFMAN   = "CONFMAN";
	public static final String DYNAMAN   = "DYNAMAN";
	public static final String DISTRIMAN = "DISTRIMAN";
	public static final String OBRMAN    = "OBRMAN";
	public static final String UPDATEMAN = "UPDATEMAN";
	public static final String HISTMAN   = "HISTMAN";

**Comment by gevegab** [comment]
fixed
